import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      <div className=" h-[10vh] fixed bottom-0 align-bottom fade-in m-auto w-full text-center flex justify-center">
        <img src="/images/celerix.png" alt="celerix image" />
      </div>
    </html>
  );
}
